version: '2'
services:
  ui:
    build: ./divelocator/
    image: "ryanm/divelocator"
    ports:
      - "3300:3300"
    links: 
      - api 
  api:
    build: ./divelocapi/
    image: "ryanm/divelocapi"
    ports:
      - "3000:3000"
    links: 
      - db
  db:
    image: "couchdb" 
    ports:
      - "5984:5984"
    volumes:
      - /var/lib/couchdb:/usr/local/var/lib/couchdb
